version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    volumes:
      - .:/app
    command: celery -A tasks worker --loglevel=info --queues=tasks --concurrency=2

  worker1:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    volumes:
      - .:/app
    command: celery -A tasks worker --loglevel=info --queues=tasks --concurrency=2

  scheduler:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    volumes:
      - .:/app

  flower:
    image: mher/flower
    container_name: flower
    depends_on:
      - rabbitmq
      - worker
    volumes:
      - ./worker/:/data
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
      - FLOWER_UNAUTHENTICATED_API=true
    ports:
      - "5555:5555"
    command: celery flower --broker=amqp://user:password@rabbitmq:5672/
